In [6]:
import numpy as np
A = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]])
print A


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
x = np.random.rand(100)
print x


[ 0.3351888   0.67154146  0.86703676  0.58884451  0.564105    0.22787447
  0.70469185  0.41699046  0.50779784  0.88083485  0.41175549  0.12916049
  0.97370424  0.54382095  0.46630337  0.23405569  0.41640952  0.79828151
  0.12459474  0.67254418  0.2529658   0.8423375   0.2489809   0.02845144
  0.85424819  0.11223926  0.40567426  0.57754281  0.0842415   0.54257902
  0.92829994  0.53360767  0.19469954  0.56804106  0.20385907  0.99350521
  0.42549415  0.76934735  0.29635196  0.16151063  0.18779607  0.86412132
  0.86326024  0.28813793  0.28812104  0.65154872  0.71024331  0.69774235
  0.59761758  0.65943431  0.2284685   0.28450807  0.44585916  0.34290105
  0.80060388  0.42001896  0.47047166  0.69191858  0.60056422  0.2349467
  0.09455136  0.39542476  0.8085796   0.83935929  0.91563954  0.65370494
  0.20159918  0.28842389  0.80780324  0.5053602   0.31829675  0.24541502
  0.24078546  0.86496731  0.27426809  0.01705274  0.1504503   0.17944573
  0.01290329  0.5513652   0.14468425  0.12246659  0.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, step=0.05)
y = np.sin(x**2)
plt.plot(x,y)
plt.show()

In [2]:
import numpy as np
x = np.arange(5)
y = -np.arange(5)
x[y < -2] = 0
import pdb; pdb.set_trace()
x *= 9
print(x)

--Return--
> <ipython-input-2-b47dc8f061eb>(5)<module>()->None
-> import pdb; pdb.set_trace()
(Pdb) 12343
12343
(Pdb) 3
3
(Pdb) start
*** NameError: name 'start' is not defined
(Pdb) x
array([0, 1, 2, 0, 0])
(Pdb) y
array([ 0, -1, -2, -3, -4])
(Pdb) s
> //anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py(2888)run_code()
-> sys.excepthook = old_excepthook
(Pdb) s
> //anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py(2904)run_code()
-> outflag = 0
(Pdb) exit


BdbQuit: 

In [16]:
 x = np.array([1,2,3,4,5])
y = x**3
y1 = x^3

print y
print y1
    

[  1   8  27  64 125]
[2 1 0 7 6]


In [20]:
data={'a': 3, 'c': 9, 'b': 5}
data['b'] = 100
print data

{'a': 3, 'c': 9, 'b': 100}


In [26]:
(x > 1).nonzero()[0][:3]

array([1, 2, 3])